buildscript {
    repositories {
        maven {
            url projectRepositoriesMavenUrl
        }
    }
}

plugins {
    id 'java'
    id 'java-library'
    id 'maven-publish'
    id 'signing'
    id 'jacoco'
    alias(libs.plugins.gradle.versions.plugin)
    alias(libs.plugins.license.gradle.plugin)
    alias(libs.plugins.grgit.gradle)
    alias(libs.plugins.spotless.plugin.gradle)
    alias(libs.plugins.version.catalog.update)

    id 'io.github.gradle-nexus.publish-plugin' version '2.0.0'
}

group = "$groupPackage" as Object
version = "$projectVersion" as Object
description = "$rootProject.name"

// import gradle files
apply from: "gradle/apply-gradle-files.gradle"

java {
    sourceCompatibility = "$projectSourceCompatibility" as Object
    toolchain {
        languageVersion = JavaLanguageVersion.of("$projectSourceCompatibility")
    }
}

tasks.withType(JavaCompile).configureEach { javaCompiler ->
    options.encoding = "UTF-8"
    // uncomment the next line for build with compiler argument -Xlint:deprecation
    // options.compilerArgs << "-Xlint:deprecation"
    // uncomment the next line for build with compiler argument -Xlint:unchecked
    // options.compilerArgs << "-Xlint:unchecked"
}

tasks.named("test") {
    it.mustRunAfter(tasks.named("jar"))
}

nexusPublishing {
    repositories {
        sonatype {
            nexusUrl.set(uri("https://s01.oss.sonatype.org/service/local/"))
            snapshotRepositoryUrl.set(uri("https://s01.oss.sonatype.org/content/repositories/snapshots/"))
            username = System.getenv("OSSRH_USERNAME") ?: ""
            password = System.getenv("OSSRH_PASSWORD") ?: ""
        }
    }
    // Optional: Timeout erhöhen für langsame Uploads
    transitionCheckOptions {
        maxRetries.set(60)
        delayBetween.set(java.time.Duration.ofSeconds(10))
    }
}
